---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caexporter
  labels:
    app.kubernetes.io/instance: caexporter
    app.kubernetes.io/name: caexporter
    app.kubernetes.io/version: "1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: caexporter
      app.kubernetes.io/name: caexporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: caexporter
        app.kubernetes.io/name: caexporter
    spec:
      serviceAccountName: caexporter
      containers:
        - name: caexporter
          image: "bringg/caexporter:latest"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caexporter
  labels:
    app.kubernetes.io/instance: caexporter
    app.kubernetes.io/name: caexporter
    app.kubernetes.io/version: "1.0"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: caexporter
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: caexporter
    app.kubernetes.io/name: caexporter
    app.kubernetes.io/version: "1.0"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - 'cluster-autoscaler-status'
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: caexporter
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: caexporter
    app.kubernetes.io/name: caexporter
    app.kubernetes.io/version: "1.0"
roleRef:
  kind: Role
  name: caexporter
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: caexporter
